### ISSUE TITLE
Mamba vs RWKV

### ISSUE THREAD

**Issue by fire** [lucidrains/meshgpt-pytorch#10]
You mentioned that you wanted to test Mamba for meshgpt, but I wanted to note that RWKV is also viable for extensible context limits.

RWKV is more elegant to me, but I am not an ML expert. 

https://github.com/BlinkDL/RWKV-LM

https://arxiv.org/abs/2305.13048

RWKV in 150 lines (model, inference, text generation): https://github.com/BlinkDL/ChatRWKV/blob/main/RWKV_in_150_lines.py

**Comment by lucidrains** [comment]
rwkv and mamba are both converging on a similar design, despite both trying to paint themselves as unique

yea don't worry about it like i said, just worry on the data portion
