### ISSUE TITLE
How to embed additional information like uvs / bones

### ISSUE THREAD

**Issue by fire** [lucidrains/meshgpt-pytorch#22]
> add an extra graph conv stage in the encoder, where vertices are enriched with their connected vertex neighbors, before aggregating into faces. make optional

Will this allow me to embed uvs or bone + bone weights? We have a huge problem with not enough training power, but I was curious.

1. uvs are per vetex. Typically [0, 1] but can be a real number

2. Bone weights and bone indices are per vertex too. 

Weights is a value from 0 to 1.

Each vertex must sum to 1.0 for all 4, 8 .. 32 .. N influences. (Typically 4. or 8.)

Bone indices can be represented as an entire bone group like a separate mesh. Like a character is represented as hips bone of the hips sections with each part of that mesh having a secondary value of [0, 1]

5. Same as the previous idea but a token representing category. Like this mesh triangle faces is 42 which means it's the "Head" vertex group.

**Comment by lucidrains** [comment]
oh no, I don't think so, I'm just curious if graph convs in stages (vertices, edges, faces) could help with the encoding.

**Comment by lucidrains** [comment]
let's move this to discussion
