### ISSUE TITLE
Issue with Multiple `eos_token_id` in Code Sequences

### ISSUE THREAD

**Issue by qixuema** [lucidrains/meshgpt-pytorch#26]
Hi, Phil,

I've noticed a potential issue in the code where multiple `eos_token_id` are being added to the [code sequences](https://github.com/lucidrains/meshgpt-pytorch/blob/8ec8f348be9b18f94b5c430337bafeb70b089281/meshgpt_pytorch/meshgpt_pytorch.py#L1280-L1283), instead of just one at the end of each row. It seems to insert four `eos_token_id` values. Could you please clarify if this is the expected behavior?

```python
batch_arange = torch.arange(batch, device = device)
batch_arange = rearrange(batch_arange, '... -> ... 1')

codes[batch_arange, code_lens] = self.eos_token_id
```

Best regards,
Xueqi

**Comment by lucidrains** [comment]
@qixuema yes indeed there was an issue of a missing dimension

thank you Xueqi!
