### ISSUE TITLE
use_heinsen

### ISSUE THREAD

**Issue by gitsawww** [lucidrains/meshgpt-pytorch#31]
Thanks for your great work!But why i get this?
![image](https://github.com/lucidrains/meshgpt-pytorch/assets/143673887/4be066f8-ea3d-416b-b2e6-b290f23135e7)

**Comment by lucidrains** [comment]
@gitsawww update to the latest gateloop-transformer `pip install gateloop-transformer -U`

**Comment by gitsawww** [comment]
> @gitsawww update to the latest gateloop-transformer `pip install gateloop-transformer -U`. or `pip install meshgpt-pytorch -U`

thank you a lot
