### ISSUE TITLE
How to preprocess ShapeNet models?

### ISSUE THREAD

**Issue by xuanyaoming** [lucidrains/meshgpt-pytorch#35]
Hi, thanks for your great work. But it's still not clear that how to preprocess the 3D models. Based on my understanding of the paper, the number of triangle faces will be reduced to 800 with a tool called "Blender". However, "blender" is not in the depencency list of this repo.  Could you kindly share an example demonstrating how your team processed the original mesh data? 

By the way, the computational cost of Autoencoder is a lot larger than GPT in my experiments. My guess is that *the Graph CNN doesn't scale well* when the number of nodes grows large (i.e. too many faces in the 3D model).  Bluring the model is one solution, but is it possible to break one giant 3D model to pieces and treat each piece as an independent model?

**Comment by MarcusLoppe** [comment]
> Hi, thanks for your great work. But it's still not clear that how to preprocess the 3D models. Based on my understanding of the paper, the number of triangle faces will be reduced to 800 with a tool called "Blender". However, "blender" is not in the depencency list of this repo. Could you kindly share an example demonstrating how your team processed the original mesh data?
> 
> By the way, the computational cost of Autoencoder is a lot larger than GPT in my experiments. My guess is that _the Graph CNN doesn't scale well_ when the number of nodes grows large (i.e. too many faces in the 3D model). Bluring the model is one solution, but is it possible to break one giant 3D model to pieces and treat each piece as an independent model?


This repo isn't the original but a recreation/improved version, lucidrains is not related to the MeshGPT paper. 
Blender isn't a requirement, they explained how they simplified the mesh so it was easier to train since it's less data and they could train on more complex models.

The total parameters of autoencoder is total around 8.8M parameters, it's very light but the residual vector quantization uses a lot of VRAM.  The transformer (100-200M) is much slower, in the paper they trained the autoencoder for 2 days using 2x A80 and the transformer for 4 days using 4x A80.

Sure, you can break it down but then the output won't fit since doesn't know how the rest looks :/

**Comment by xuanyaoming** [comment]
> > Hi, thanks for your great work. But it's still not clear that how to preprocess the 3D models. Based on my understanding of the paper, the number of triangle faces will be reduced to 800 with a tool called "Blender". However, "blender" is not in the depencency list of this repo. Could you kindly share an example demonstrating how your team processed the original mesh data?
> > By the way, the computational cost of Autoencoder is a lot larger than GPT in my experiments. My guess is that _the Graph CNN doesn't scale well_ when the number of nodes grows large (i.e. too many faces in the 3D model). Bluring the model is one solution, but is it possible to break one giant 3D model to pieces and treat each piece as an independent model?
> 
> This repo isn't the original but a recreation/improved version, lucidrains is not related to the MeshGPT paper. Blender isn't a requirement, they explained how they simplified the mesh so it was easier to train since it's less data and they could train on more complex models.
> 
> The total parameters of autoencoder is total around 8.8M parameters, it's very light but the residual vector quantization uses a lot of VRAM. The transformer (100-200M) is much slower, in the paper they trained the autoencoder for 2 days using 2x A80 and the transformer for 4 days using 4x A80.
> 
> Sure, you can break it down but then the output won't fit since doesn't know how the rest looks :/

Many thanks for your reply. The mesh I was using has more than 3000 faces, and the quantization phase tried to assign VRAM for all nodes at the same time. That's why my experiment failed using 4x A100. 
I'll see whether there is a better quantization algorithm to use, or is it possible to only process part of a large mesh each time.

**Comment by MarcusLoppe** [comment]
> > > Hi, thanks for your great work. But it's still not clear that how to preprocess the 3D models. Based on my understanding of the paper, the number of triangle faces will be reduced to 800 with a tool called "Blender". However, "blender" is not in the depencency list of this repo. Could you kindly share an example demonstrating how your team processed the original mesh data?
> > > By the way, the computational cost of Autoencoder is a lot larger than GPT in my experiments. My guess is that _the Graph CNN doesn't scale well_ when the number of nodes grows large (i.e. too many faces in the 3D model). Bluring the model is one solution, but is it possible to break one giant 3D model to pieces and treat each piece as an independent model?
> > 
> > 
> > This repo isn't the original but a recreation/improved version, lucidrains is not related to the MeshGPT paper. Blender isn't a requirement, they explained how they simplified the mesh so it was easier to train since it's less data and they could train on more complex models.
> > The total parameters of autoencoder is total around 8.8M parameters, it's very light but the residual vector quantization uses a lot of VRAM. The transformer (100-200M) is much slower, in the paper they trained the autoencoder for 2 days using 2x A80 and the transformer for 4 days using 4x A80.
> > Sure, you can break it down but then the output won't fit since doesn't know how the rest looks :/
> 
> Many thanks for your reply. The mesh I was using has more than 3000 faces, and the quantization phase tried to assign VRAM for all nodes at the same time. That's why my experiment failed using 4x A100. I'll see whether there is a better quantization algorithm to use, or is it possible to only process part of a large mesh each time.

It may be the due to the face_edges, it uses a lot VRAM when it generates these during runtime. For example; it used 6 GB for 1 batch of 6000 faces.  
If you were using lets say batch size of 16x 6GB = 96GB VRAM. So it's really important to generate these beforehand. 

If you generate the face_edges and save the dataset, you can then restart the session to clear the VRAM and load them back, the 6000 faces mesh then only used 500 MB.

https://github.com/lucidrains/meshgpt-pytorch/pull/37/commits/68693ac560123a04931575eca8e0fcc197e2f5a6

**Comment by xuanyaoming** [comment]
> > > > Hi, thanks for your great work. But it's still not clear that how to preprocess the 3D models. Based on my understanding of the paper, the number of triangle faces will be reduced to 800 with a tool called "Blender". However, "blender" is not in the depencency list of this repo. Could you kindly share an example demonstrating how your team processed the original mesh data?
> > > > By the way, the computational cost of Autoencoder is a lot larger than GPT in my experiments. My guess is that _the Graph CNN doesn't scale well_ when the number of nodes grows large (i.e. too many faces in the 3D model). Bluring the model is one solution, but is it possible to break one giant 3D model to pieces and treat each piece as an independent model?
> > > 
> > > 
> > > This repo isn't the original but a recreation/improved version, lucidrains is not related to the MeshGPT paper. Blender isn't a requirement, they explained how they simplified the mesh so it was easier to train since it's less data and they could train on more complex models.
> > > The total parameters of autoencoder is total around 8.8M parameters, it's very light but the residual vector quantization uses a lot of VRAM. The transformer (100-200M) is much slower, in the paper they trained the autoencoder for 2 days using 2x A80 and the transformer for 4 days using 4x A80.
> > > Sure, you can break it down but then the output won't fit since doesn't know how the rest looks :/
> > 
> > 
> > Many thanks for your reply. The mesh I was using has more than 3000 faces, and the quantization phase tried to assign VRAM for all nodes at the same time. That's why my experiment failed using 4x A100. I'll see whether there is a better quantization algorithm to use, or is it possible to only process part of a large mesh each time.
> 
> @xuanyaoming
> 
> I don't think that the quantizer is the issue then since you are using 4x A100. It may be the due to the face_edges, it uses a lot VRAM when it generates these during runtime. For example; i convert 6000 faces using a batch size of 1, it used 6 GB VRAM. If you were using lets say batch size of 16x 6GB = 96GB VRAM. So it's really important to generate these beforehand.
> 
> If you generate the face_edges and save the dataset, you can then restart the session to clear the VRAM and load them back, the 6000 faces mesh then only used 500 MB.
> 
> Take a look at how I do it in the pull request below. [Mesh dataset pull request](https://github.com/lucidrains/meshgpt-pytorch/pull/37/commits/68693ac560123a04931575eca8e0fcc197e2f5a6)
> 
> Really awesome that you have access to so many powerful GPU's, I raised the quantizer VRAM issue due to I'm trying to optimize it to run it using 16 GB VRAM. Don't forget to augment the data so it can generalize better, you can reuse the same face_edges for a 3D model and it's variations since you not changing the faces but just the positions.

I'm not entirely sure whether you were talking about training phase or inference phase. But if you were talking about training, then the real issue in my program is probably the configs of *huggingface accelerate*, as the mesh data and batch_size I was using is smaller than yours (4000 faces and 1 batch_size). I also observed the GPU VRAM usage grew 10 times larger during inference while launching with *accelerate*, but the inference speed didn't improve much. To be honest, I'm not an expert in multi-GPU training, so the analysis above is just my personal speculation.

However, VRAM bottleneck is definitely a major issue. Because I also tried to train the autoencoder without *huggingface accelerate*, and it didn't work either. The error message was "out of memory". I'll see what I can do to reduce VRAM.

**Comment by MarcusLoppe** [comment]
> I'm not entirely sure whether you were talking about training phase or inference phase. But if you were talking about training, then the real issue in my program is probably the configs of _huggingface accelerate_, as the mesh data and batch_size I was using is smaller than yours (4000 faces and 1 batch_size). 

I was talking about the training. During the training the autoencoder needs something called face_edges, these are used for the ConvSage to connect the faces. 
If face_edges isn't passed to the model's forward when training it needs to generate these by itself, this is done by calling the function **derive_face_edges_from_faces** . 

This function is very expensive since it process the entire batch at the same time. If you have 5k faces and 16 batch size, it generates 98GB VRAM.
The faces edges won't be saved since this responsibility belongs to the dataset, so each step this happens every time.

To avoid this problem; you can preprocess the mesh and generate the face_edges and save tons of VRAM. [see here](https://github.com/lucidrains/meshgpt-pytorch/pull/37/commits/68693ac560123a04931575eca8e0fcc197e2f5a6)

>I also observed the GPU VRAM usage grew 10 times larger during inference while launching with _accelerate_, but the inference speed didn't improve much. To be honest, I'm not an expert in multi-GPU training, so the analysis above is just my personal speculation.
> 
I haven't tried using accelerate when inferencing and got no experience multi-GPU so I cannot help at the moment:/

> However, VRAM bottleneck is definitely a major issue. Because I also tried to train the autoencoder without _huggingface accelerate_, and it didn't work either. The error message was "out of memory". I'll see what I can do to reduce VRAM.

What is the max count of faces & vertices of the mesh your training on?
Are you using the face_edges in the dataset? I can train the autoencoder on mesh models with 3200 faces and 1400 vertices models using my 3060 using 9.7 GB at 4 batch size, so I don't it's a model problem (unless it's directly related to multi-gpu)
 
I found it helpful to also normalize and remove the duplicate vertexes when preprocessing, are you also sorting the faces by lowest vertex index & vertices by yxz (where y = vertical). 


```
def get_mesh(file_path): 
    mesh = trimesh.load(file_path, force='mesh')
     
    vertices = mesh.vertices.tolist()
    faces = mesh.faces.tolist()
    centered_vertices = vertices - np.mean(vertices, axis=0) 
    max_abs = np.max(np.abs(centered_vertices))
    
    vertices = centered_vertices / (max_abs / 0.95)  
      
      
    def sort_vertices(vertex):
        return vertex[1], vertex[0], vertex[2]   
 
    seen = OrderedDict()
    for point in vertices: 
      key = tuple(point)
      if key not in seen:
        seen[key] = point
        
    unique_vertices =  list(seen.values()) 
    sorted_vertices = sorted(unique_vertices, key=sort_vertices)
     
    vertices_as_tuples = [tuple(v) for v in vertices]
    sorted_vertices_as_tuples = [tuple(v) for v in sorted_vertices]

    vertex_map = {old_index: new_index for old_index, vertex_tuple in enumerate(vertices_as_tuples) for new_index, sorted_vertex_tuple in enumerate(sorted_vertices_as_tuples) if vertex_tuple == sorted_vertex_tuple}
  
    reindexed_faces = [[vertex_map[face[0]], vertex_map[face[1]], vertex_map[face[2]]] for face in faces] 
    return np.array(sorted_vertices), np.array(reindexed_faces)
```

**Comment by xuanyaoming** [comment]
> > I'm not entirely sure whether you were talking about training phase or inference phase. But if you were talking about training, then the real issue in my program is probably the configs of _huggingface accelerate_, as the mesh data and batch_size I was using is smaller than yours (4000 faces and 1 batch_size).
> 
> I was talking about the training. During the training the autoencoder needs something called face_edges, these are used for the ConvSage to connect the faces. If face_edges isn't passed to the model's forward when training it needs to generate these by itself, this is done by calling the function **derive_face_edges_from_faces** .
> 
> This function is very expensive since it process the entire batch at the same time. If you have 5k faces and 16 batch size, it generates 98GB VRAM. The faces edges won't be saved since this responsibility belongs to the dataset, so each step this happens every time.
> 
> To avoid this problem; you can preprocess the mesh and generate the face_edges and save tons of VRAM. [see here](https://github.com/lucidrains/meshgpt-pytorch/pull/37/commits/68693ac560123a04931575eca8e0fcc197e2f5a6)
> 
> > I also observed the GPU VRAM usage grew 10 times larger during inference while launching with _accelerate_, but the inference speed didn't improve much. To be honest, I'm not an expert in multi-GPU training, so the analysis above is just my personal speculation.
> 
> I haven't tried using accelerate when inferencing and got no experience multi-GPU so I cannot help at the moment:/
> 
> > However, VRAM bottleneck is definitely a major issue. Because I also tried to train the autoencoder without _huggingface accelerate_, and it didn't work either. The error message was "out of memory". I'll see what I can do to reduce VRAM.
> 
> What is the max count of faces & vertices of the mesh your training on? Are you using the face_edges in the dataset? I can train the autoencoder on mesh models with 3200 faces and 1400 vertices models using my 3060 using 9.7 GB at 4 batch size, so I don't it's a model problem (unless it's directly related to multi-gpu)
> 
> I found it helpful to also normalize and remove the duplicate vertexes when preprocessing, are you also sorting the faces by lowest vertex index & vertices by yxz (where y = vertical).
> 
> ```
> def get_mesh(file_path): 
>     mesh = trimesh.load(file_path, force='mesh')
>      
>     vertices = mesh.vertices.tolist()
>     faces = mesh.faces.tolist()
>     centered_vertices = vertices - np.mean(vertices, axis=0) 
>     max_abs = np.max(np.abs(centered_vertices))
>     
>     vertices = centered_vertices / (max_abs / 0.95)  
>       
>       
>     def sort_vertices(vertex):
>         return vertex[1], vertex[0], vertex[2]   
>  
>     seen = OrderedDict()
>     for point in vertices: 
>       key = tuple(point)
>       if key not in seen:
>         seen[key] = point
>         
>     unique_vertices =  list(seen.values()) 
>     sorted_vertices = sorted(unique_vertices, key=sort_vertices)
>      
>     vertices_as_tuples = [tuple(v) for v in vertices]
>     sorted_vertices_as_tuples = [tuple(v) for v in sorted_vertices]
> 
>     vertex_map = {old_index: new_index for old_index, vertex_tuple in enumerate(vertices_as_tuples) for new_index, sorted_vertex_tuple in enumerate(sorted_vertices_as_tuples) if vertex_tuple == sorted_vertex_tuple}
>   
>     reindexed_faces = [[vertex_map[face[0]], vertex_map[face[1]], vertex_map[face[2]]] for face in faces] 
>     return np.array(sorted_vertices), np.array(reindexed_faces)
> ```

Thanks for your codes. I didn't realize some vertices could be duplicate. As to the size of 3D assets, the max number of faces I observed was over 6K, and the subsequent number of face edges can reach 48358116 (really big, isn't it?). The GPUs were able to process them ( with proper configurations ) at first but soon failed on smaller data ( with only 233 faces and 50K face edges ).

I managed to rewrite and optimize the `encode` function of `MeshAutoencoder`, shrinked the space complexity of generating `face_coords` into O(n) (See my codes below), and disable the linear attention layer in the encoder modules temporarily. None of the effort works  because the `SAGEConv` layer can't handle large graphs. The only way to make meshGPT support high resolution 3D assets is to replace the graph convolution layer.

```
face_without_pad = faces.masked_fill(~rearrange(face_mask, 'b nf -> b nf 1'), 0)
partial_flattened_face_vertices = repeat(face_without_pad.view(batch, -1), 'b x -> b x c', c=num_coors)
face_coords = torch.gather(vertices, dim=1, index=partial_flattened_face_vertices).view(batch, num_faces, 3, num_coors)
```

**Comment by MarcusLoppe** [comment]
> > > I'm not entirely sure whether you were talking about training phase or inference phase. But if you were talking about training, then the real issue in my program is probably the configs of _huggingface accelerate_, as the mesh data and batch_size I was using is smaller than yours (4000 faces and 1 batch_size).
> > 
> > 
> > I was talking about the training. During the training the autoencoder needs something called face_edges, these are used for the ConvSage to connect the faces. If face_edges isn't passed to the model's forward when training it needs to generate these by itself, this is done by calling the function **derive_face_edges_from_faces** .
> > This function is very expensive since it process the entire batch at the same time. If you have 5k faces and 16 batch size, it generates 98GB VRAM. The faces edges won't be saved since this responsibility belongs to the dataset, so each step this happens every time.
> > To avoid this problem; you can preprocess the mesh and generate the face_edges and save tons of VRAM. [see here](https://github.com/lucidrains/meshgpt-pytorch/pull/37/commits/68693ac560123a04931575eca8e0fcc197e2f5a6)
> > > I also observed the GPU VRAM usage grew 10 times larger during inference while launching with _accelerate_, but the inference speed didn't improve much. To be honest, I'm not an expert in multi-GPU training, so the analysis above is just my personal speculation.
> > 
> > 
> > I haven't tried using accelerate when inferencing and got no experience multi-GPU so I cannot help at the moment:/
> > > However, VRAM bottleneck is definitely a major issue. Because I also tried to train the autoencoder without _huggingface accelerate_, and it didn't work either. The error message was "out of memory". I'll see what I can do to reduce VRAM.
> > 
> > 
> > What is the max count of faces & vertices of the mesh your training on? Are you using the face_edges in the dataset? I can train the autoencoder on mesh models with 3200 faces and 1400 vertices models using my 3060 using 9.7 GB at 4 batch size, so I don't it's a model problem (unless it's directly related to multi-gpu)
> > I found it helpful to also normalize and remove the duplicate vertexes when preprocessing, are you also sorting the faces by lowest vertex index & vertices by yxz (where y = vertical).
> > ```
> > def get_mesh(file_path): 
> >     mesh = trimesh.load(file_path, force='mesh')
> >      
> >     vertices = mesh.vertices.tolist()
> >     faces = mesh.faces.tolist()
> >     centered_vertices = vertices - np.mean(vertices, axis=0) 
> >     max_abs = np.max(np.abs(centered_vertices))
> >     
> >     vertices = centered_vertices / (max_abs / 0.95)  
> >       
> >       
> >     def sort_vertices(vertex):
> >         return vertex[1], vertex[0], vertex[2]   
> >  
> >     seen = OrderedDict()
> >     for point in vertices: 
> >       key = tuple(point)
> >       if key not in seen:
> >         seen[key] = point
> >         
> >     unique_vertices =  list(seen.values()) 
> >     sorted_vertices = sorted(unique_vertices, key=sort_vertices)
> >      
> >     vertices_as_tuples = [tuple(v) for v in vertices]
> >     sorted_vertices_as_tuples = [tuple(v) for v in sorted_vertices]
> > 
> >     vertex_map = {old_index: new_index for old_index, vertex_tuple in enumerate(vertices_as_tuples) for new_index, sorted_vertex_tuple in enumerate(sorted_vertices_as_tuples) if vertex_tuple == sorted_vertex_tuple}
> >   
> >     reindexed_faces = [[vertex_map[face[0]], vertex_map[face[1]], vertex_map[face[2]]] for face in faces] 
> >     return np.array(sorted_vertices), np.array(reindexed_faces)
> > ```
> 
> Thanks for your codes. I didn't realize some vertices could be duplicate. As to the size of 3D assets, the max number of faces I observed was over 6K, and the subsequent number of face edges can reach 48358116 (really big, isn't it?). The GPUs were able to process them ( with proper configurations ) at first but soon failed on smaller data ( with only 233 faces and 50K face edges ).
> 
> I managed to rewrite and optimize the `encode` function of `MeshAutoencoder`, shrinked the space complexity of generating `face_coords` into O(n) (See my codes below), and disable the linear attention layer in the encoder modules temporarily. None of the effort works because the `SAGEConv` layer can't handle large graphs. The only way to make meshGPT support high resolution 3D assets is to replace the graph convolution layer.
> 
> ```
> face_without_pad = faces.masked_fill(~rearrange(face_mask, 'b nf -> b nf 1'), 0)
> partial_flattened_face_vertices = repeat(face_without_pad.view(batch, -1), 'b x -> b x c', c=num_coors)
> face_coords = torch.gather(vertices, dim=1, index=partial_flattened_face_vertices).view(batch, num_faces, 3, num_coors)
> ```

Oh, I think I understand your issue. 
I can't remember the specifics but when I created the generate_face_edges I tested with chunking the faces together and created batches e.g [4, faces,4 ]. But the face_edges that returned was way too big for all the faces. 

When I padded the batches I used 0 as padding, but since 0 is a valid index to the vertex list, it thought it was a valid face edge. 
Instead of padding with 0 I should have used pad_id which is -1.
If you are creating your own trainer, keep in mind to pad the batches with -1 instead of zeros. 

Here is the correct face edges count:
```
faces  torch.Size([6206, 3])
vertices  torch.Size([3199, 3])
face_edges  torch.Size([24706, 2])

faces  torch.Size([3232, 3])
vertices  torch.Size([1630, 3])
face_edges  torch.Size([12928, 2])
```

**Comment by xuanyaoming** [comment]
> Oh, I think I understand your issue. When I generated the face edges I tested with chunking the faces together and created batches e.g [4, faces, 3 ]. but the return edges was too many to make sense.
> 
> When I padded the batches I used 0 as padding, but since 0 is a valid index to the vertex list, it threaded it was a valid face edge and created padding_amount * padding_amount face edges.
> 
> Instead of padding with 0 I should have used pad_id which is -1. So take a look and see if this is the problem, I find it better to use a batch size of 1 since the data wont be padded and is using minimal VRAM to find the edges.
> 
> Here is a example of some meshes and the correct face edges count:
> 
> ```
> faces  torch.Size([6206, 3])
> vertices  torch.Size([3199, 3])
> face_edges  torch.Size([24706, 2])
> 
> faces  torch.Size([3232, 3])
> vertices  torch.Size([1630, 3])
> face_edges  torch.Size([12928, 2])
> ```

Thanks a lot for your idea. However I don't think that's the issue, because I was using the default pad_id which is -1. Additionally, I was using the "plane" category of ShapeNetV2. The data is very clean and should have already been normalized and filtered. I tried preprocessing the dataset with your code but the results were identical. The final solution I chose was simply dropping all meshes whose number of faces are larger than 4000. It works for now, at the expense of losing large portion of the dataset.

Personally, the ideal solution I was hoping for is an open-source mesh quantizer, or any other function that can replace the graph convolutional layers efficiently. A preprocessing technique that can both simplify meshes and preserve all notable features is also good enough. I'll settle with dropping complex meshes for now but open for new ideas.

**Comment by MarcusLoppe** [comment]
> > Oh, I think I understand your issue. When I generated the face edges I tested with chunking the faces together and created batches e.g [4, faces, 3 ]. but the return edges was too many to make sense.
> > When I padded the batches I used 0 as padding, but since 0 is a valid index to the vertex list, it threaded it was a valid face edge and created padding_amount * padding_amount face edges.
> > Instead of padding with 0 I should have used pad_id which is -1. So take a look and see if this is the problem, I find it better to use a batch size of 1 since the data wont be padded and is using minimal VRAM to find the edges.
> > Here is a example of some meshes and the correct face edges count:
> > ```
> > faces  torch.Size([6206, 3])
> > vertices  torch.Size([3199, 3])
> > face_edges  torch.Size([24706, 2])
> > 
> > faces  torch.Size([3232, 3])
> > vertices  torch.Size([1630, 3])
> > face_edges  torch.Size([12928, 2])
> > ```
> 
> Thanks a lot for your idea. However I don't think that's the issue, because I was using the default pad_id which is -1. Additionally, I was using the "plane" category of ShapeNetV2. The data is very clean and should have already been normalized and filtered. I tried preprocessing the dataset with your code but the results were identical. The final solution I chose was simply dropping all meshes whose number of faces are larger than 4000. It works for now, at the expense of losing large portion of the dataset.
> 
> Personally, the ideal solution I was hoping for is an open-source mesh quantizer, or any other function that can replace the graph convolutional layers efficiently. A preprocessing technique that can both simplify meshes and preserve all notable features is also good enough. I'll settle with dropping complex meshes for now but open for new ideas.

That is very weird, I'm not actually sure if that's the model fault. Having 48 358 116 face edges is 100% an error.
I also have access to the shapenet dataset so could you provide me with the filename(s) for the mesh that have such high count of face edges?

The quantizer doesn't input any face edges, only the faces and it's embeddings of the ConvSage e.g [Faces x 576].
I've tried with 6k faces and it only got up to 5-7GB in VRAM when training the autoencoder. 
However the ConvSage does input the face edges but it's a tiny model with 600k parameters and the VRAM barely moved when I tried a 16k face mesh.

**Comment by xuanyaoming** [comment]
> I also have access to the shapenet dataset so could you provide me with the file/folder name(s) for the mesh that have such high count of face edges?

Sure, the 3D asset works for me is `02691156/feb0bd0dcd155af4cc34b900bb2492e/models/model_normalized.obj`, with 607 faces and 367236 face edges. Another bigger example is `02691156/fdb107ea7a600f5fe3f3aec01b086ba/models/model_normalized.obj`, with 3555 faces and 6687396 face edges. A more complex one is `02691156/ece25d89898c7d9090b1d6deb98feec6/models/model_normalized.obj`, with 5511 faces and 30360100 face edges. The number of face edges is printed from the the shape of `face_edges` tensor in the `encoder` function of `MeshAutoencoder` before it's passed into the for-loop. I agree that there is an error, because in the last example it's unlikely for one face node to have 10k neighbors on average, considering there are only 5k face nodes in total. 



> However the ConvSage does input the face edges but it's a tiny model with 600k parameters and the VRAM barely moved when I tried a 16k face mesh.

The reason for your success is that the number of face edges is small. Pytorch has to allocate extra memories in the computational graph for each face edge in the ConvSage phase, which is why it needed so much VRAM in my experiments. I agree that the number of trainable parameters is not the issue here, because both the autoencoder and GPT2 are small models.

Anyway, I'll recheck `derive_face_edges_from_faces` function in `data.py`. That's where the problem most likely lies.

**Comment by MarcusLoppe** [comment]
> Sure, the 3D asset works for me is `02691156/feb0bd0dcd155af4cc34b900bb2492e/models/model_normalized.obj`, with 607 faces and 367236 face edges. Another bigger example is `02691156/fdb107ea7a600f5fe3f3aec01b086ba/models/model_normalized.obj`, with 3555 faces and 6687396 face edges. A more complex one is `02691156/ece25d89898c7d9090b1d6deb98feec6/models/model_normalized.obj`, with 5511 faces and 30360100 face edges. The number of face edges is printed from the the shape of `face_edges` tensor in the `encoder` function of `MeshAutoencoder` before it's passed into the for-loop. I agree that there is an error, because in the last example it's unlikely for one face node to have 10k neighbors on average, considering there are only 5k face nodes in total.
> 
 
Thank you, I checked the shapenet files but I'm getting different face count then you.
The only file i managed to generate face edges was the feb0bd0dcd155af4cc34b900bb2492e and I got 4868 face_edges.
I think there has been some mistake since those other meshes has 44k and 157k faces, how are you loading the meshes or counting the faces? 

I checked the [glb dataset](https://huggingface.co/datasets/ShapeNet/shapenetcore-glb) and [ShapeNetCore](https://huggingface.co/datasets/ShapeNet/ShapeNetCore-archive) but the face count was same for both.
Here are the files I checked if you want to double check:  https://file.io/A2FtnExPHbWv

ece25d89898c7d9090b1d6deb98feec6: 44 410 face/triangles 
fdb107ea7a600f5fe3f3aec01b086ba: 157 302 face/triangles 

```
File:  feb0bd0dcd155af4cc34b900bb2492e.obj
Faces  torch.Size([606, 3])
Vertices  torch.Size([163, 3])
face_edges  torch.Size([4868, 2])

``` 

![bild](https://github.com/lucidrains/meshgpt-pytorch/assets/65302107/78476894-b391-4eb6-bb9a-c498eeef6c52)

**Comment by xuanyaoming** [comment]
> Anyway, I'll recheck `derive_face_edges_from_faces` function in `data.py`. That's where the problem most likely lies.

Fixed the issue. The version of meshGPT I installed with pip isn't up-to-date. By adding parentheses around `num_shared_vertices >= face_edges_vertices_threshold` in the `derive_face_edges_from_faces` function can reduce the number of face edges to normal. The contributors must have noticed the bug and fixed it two weeks ago, but somehow the pip version wasn't updated.

> Thank you, I checked the shapenet files but I'm getting different face count then you. The only file i managed to generate face edges was the feb0bd0dcd155af4cc34b900bb2492e and I got 4868 face_edges. I think there has been some mistake since those other meshes has 44k and 157k faces, how are you loading the meshes or counting the faces?
> 
> I checked the [glb dataset](https://huggingface.co/datasets/ShapeNet/shapenetcore-glb) and [ShapeNetCore](https://huggingface.co/datasets/ShapeNet/ShapeNetCore-archive) but the face count was same for both. Here are the files I checked if you want to double check: https://file.io/A2FtnExPHbWv
> 
> ece25d89898c7d9090b1d6deb98feec6: 44 410 face/triangles fdb107ea7a600f5fe3f3aec01b086ba: 157 302 face/triangles

Thanks a lot for checking the 3D sasset files. But the file name is a little bit incorrect. I was using the normalized version of the same 3D asset, downloaded from [this link](https://huggingface.co/datasets/ShapeNet/ShapeNetCore). Maybe normalization made the number of faces smaller? By the way, where did you download the original dataset?

**Comment by xuanyaoming** [comment]
> Have you as well used derive_face_edges_from_faces when you are processing and creating the dataset? Since when AutoEncoder is creating the face_edges, it wont save due to it uses a copy of the dataset that is created by dataloader, also; it does the entire batch the same time so that will generate a lot of VRAM.

No, I didn't do that. But in the encoder function, MeshAutoencoder will do it automatically.

**Comment by MarcusLoppe** [comment]
>
> Fixed the issue. The version of meshGPT I installed with pip isn't up-to-date. By adding parentheses around `num_shared_vertices >= face_edges_vertices_threshold` in the `derive_face_edges_from_faces` function can reduce the number of face edges to normal. The contributors must have noticed the bug and fixed it two weeks ago, but somehow the pip version wasn't updated.
> 
Ah that's great! 
 
> Thanks a lot for checking the 3D sasset files. But the file name is a little bit incorrect. I was using the normalized version of the same 3D asset, downloaded from [this link](https://huggingface.co/datasets/ShapeNet/ShapeNetCore). Maybe normalization made the number of faces smaller? By the way, where did you download the original dataset?
>

Oh I extracted and renamed it, it had the same path in the zip file (ShapeNetCoreV2).
The original name was: 
`ShapeNetCore.v2.zip\ShapeNetCore.v2\02691156\ece25d89898c7d9090b1d6deb98feec6\models\model_normalized.obj`

The data should be the same, I got access to the glb (version 2)  and the ShapeNetCore-archive (both v1 and v2). Take a look at the 3d mesh files I uploaded and let me know if it's the same or you can view yours on [3dviewer](https://3dviewer.net/) to get a accurate face count.

I got both the versions of it since the v1 is the only one that contains the labels and tags. Example:
```
fullId,wnsynset,wnlemmas,up,front,name,tags
3dw.a4678e6798e768c3b6a66ea321171690,"02842573,04012084,02691156","biplane,propeller plane,airplane,aeroplane,plane","0.0\,0.0\,1.0","0.0\,1.0\,0.0",Old-school Yellow Biplane,
``` 
 
> > Have you as well used derive_face_edges_from_faces when you are processing and creating the dataset? Since when AutoEncoder is creating the face_edges, it wont save due to it uses a copy of the dataset that is created by dataloader, also; it does the entire batch the same time so that will generate a lot of VRAM.
> 
> No, I didn't do that. But in the encoder function, MeshAutoencoder will do it automatically.

Correct, but since it sets the faces to the copy that exists in the dataloader, it vanishes and not saved. I'm not sure if it's removed each time it cycles but if you preprocess the face_edges you wont need to preprocess 16 or 32 meshes at same time due to the batch size.

**Comment by xuanyaoming** [comment]
> ece25d89898c7d9090b1d6deb98feec6: 44 410 face/triangles
> fdb107ea7a600f5fe3f3aec01b086ba: 157 302 face/triangles

Rechecked my codes. I mixed up the outputs of those data items because they were processed in parallel. The numbers generated by my code matches the yours. I hope that means my mesh reader is safe to use.

**Comment by MarcusLoppe** [comment]
> > ece25d89898c7d9090b1d6deb98feec6: 44 410 face/triangles
> > fdb107ea7a600f5fe3f3aec01b086ba: 157 302 face/triangles
> 
> Rechecked my codes. I mixed up the outputs of those data items because they were processed in parallel. The numbers generated by my code matches the yours. I hope that means my mesh reader is safe to use.

Ah great, I'm guessing that you resolved your issue and no longer have the issue about huge numbers of face edges?

You should then be fine to train on 6k face meshes without any VRAM issues.

**Comment by xuanyaoming** [comment]
> Ah great, I'm guessing that you resolved your issue and no longer have the issue about huge numbers of face edges?
> 
> You should then be fine to train on 6k face meshes without any VRAM issues.

VRAM issues always exist. Because expanding GPT sequence length also leads to out-of-memory.  But I think seperate autoencoder from transformer will help a lot, Another solution in my mind is mixed-precision training, which should be able to reduce the VRAM usage to half. If neither solution works, I will consider replace GPT with the latest varients. A lot of recent papers are relating to this topic.

Anyway, I'll close this issue for now.

**Comment by MarcusLoppe** [comment]
> > Ah great, I'm guessing that you resolved your issue and no longer have the issue about huge numbers of face edges?
> > You should then be fine to train on 6k face meshes without any VRAM issues.
> 
> VRAM issues always exist. Because expanding GPT sequence length also leads to out-of-memory. But I think seperate autoencoder from transformer will help a lot, Another solution in my mind is mixed-precision training, which should be able to reduce the VRAM usage to half. If neither solution works, I will consider replace GPT with the latest varients. A lot of recent papers are relating to this topic.
> 
> Anyway, I'll close this issue for now
.
@xuanyaoming 
But the autoencoder is already separate, after the autoencoder generates the codes it's finished and never ran again while training. 
So if you generate the codes beforehand you'll never need to run the autoencoder together with the transformer.
