### ISSUE TITLE
Residual quantization - VRAM  bottleneck

### ISSUE THREAD

**Issue by MarcusLoppe** [lucidrains/meshgpt-pytorch#36]
This might be a issue related to the [vector-quantize-pytorch](https://github.com/lucidrains/vector-quantize-pytorch) but I'll bring it up here. 

During some testing I discovered that the vector quantizer took up most VRAM. I'm not sure if this is a bug or the requirements of the quantizer.

After calling Encode() it used up about 500MB and decode uses about 300MB. After calling the quantize() it used about 4 116MB, if this could be resolved, the VRAM issues might be resolved as well.  
I saw no signifiant difference using ResidualLFQ or ResidualVQ.
 
I tested with a big 3D model with 5956 vertices and 3k faces with batch size 1, the issue remains if you use a smaller 3d model. 
I setup a bunch of debug prints to monitor VRAM, here is the results after calling autoendcoder.forward()
___ 
Autoencoder - forward start: 3064.0 MB
After encode() call : 3564.0 MB

Calling quantize():
ResidualLFQ - Forward: : 3564.0 MB
ResidualLFQ - for quantizer_index, layer in enumerate(self.layers)

LFQ layer 1:
Start VRAM : 3564.0 MB 
`distance = -2 * einsum('... i d, j d -> ... i j', original_input, self.codebook)`
4312.0 MB    distance : torch.Size([1, 5956, 1, 16384])  original_input: torch.Size([1, 5956, 1, 14])  self.codebook: torch.Size([16384, 14])

`prob = (-distance * inv_temperature).softmax(dim = -1)`
4686.0 MB    prob: torch.Size([1, 5956, 1, 16384])

`per_sample_entropy = entropy(prob).mean()`
5808.0 MB  per_sample_entropy: 1.1416213512420654

`entropy_aux_loss = per_sample_entropy - self.diversity_gamma * codebook_entropy`
5856.0 MB    entropy_aux_loss: -0.8769185543060303

LFQ layer 2:
Start VRAM : 5808.0 MB 
`distance = -2 * einsum('... i d, j d -> ... i j', original_input, self.codebook)`
6184.0 MB   distance : torch.Size([1, 5956, 1, 16384])  original_input: torch.Size([1, 5956, 1, 14])  self.codebook: torch.Size([16384, 14])

`prob = (-distance * inv_temperature).softmax(dim = -1)`
6558.0 MB    prob: torch.Size([1, 5956, 1, 16384])

`per_sample_entropy = entropy(prob).mean()`
7680.0 MB  per_sample_entropy: 0.0

`entropy_aux_loss = per_sample_entropy - self.diversity_gamma * codebook_entropy`
7728.0 MB    entropy_aux_loss: -1.3798797130584717

 
After calling quantize(): 7680.0 MB
After calling decoded() : 7937.0 MB 

Step #2:
Autoencoder - forward start:  9095.0 MB 

___ 
![bild](https://github.com/lucidrains/meshgpt-pytorch/assets/65302107/f973361e-7022-4c02-b4a7-803f800c7c89)
I don't think MeshDiscretizer can be used as a solution since I think they already tried it in paper and got quite bad results.

**Comment by lucidrains** [comment]
@MarcusLoppe ohh thanks for the analysis

yea let us look into gradient checkpointing after the holidays

have a great new years!

**Comment by MarcusLoppe** [comment]
> @MarcusLoppe ohh thanks for the analysis
> 
> yea let us look into gradient checkpointing after the holidays
> 
> have a great new years!
> 
> ps: i missed that ablation; it looks good. i'll remove the mesh discretizer in january

Oh, sorry for interrupting the vacation. 😢 
I posted since didn't want to need to remember this info till next year. 

Likewise, happy new year 🎉

**Comment by lucidrains** [comment]
@MarcusLoppe hey circling back to this. will try to get recomputed gradients working for the quantization module by tonight

**Comment by lucidrains** [comment]
@MarcusLoppe i added [memory checkpointing](https://pytorch.org/docs/stable/checkpoint.html) in the latest version, which can be turned on by setting `checkpoint_quantizer = True` on the autoencoder

do you want to check to see if this reduces the memory usage you observe?

**Comment by MarcusLoppe** [comment]
> @MarcusLoppe i added [memory checkpointing](https://pytorch.org/docs/stable/checkpoint.html) in the latest version, which can be turned on by setting `checkpoint_quantizer = True` on the autoencoder
> 
> do you want to check to see if this reduces the memory usage you observe?

@lucidrains  
Great, I'll check this out tonight.

Btw, do you have good ideas to replace the Resnet34? I've tried using Resnet50 but since it's downsampling the output shape isn't the same, even if I use a upsampling (since the downsampling takes a e.g uneven number of faces 239 and reduces it to 120, then the upsampling will increase to 240 and make the output invalid).
Any idea for improving the ConvSage? Maybe through in a flash attention layer? :) 

I'm asking this due to the ConvSage, Resnet and the codebook needs to get a lot better, the models and codebook aren't big to handle generalized mesh.
In the paper they pre-trained it on all meshes, then fine-tuned it on specific category's e.g chair.
This means that the models and codebook doesn't need to be that big since it only needs to be able to store one type of model pattern. I'd imagine that storing the patterns of how a chair triangles look might not require such a big codebook.

When I trained the autoencoder on 4 different categories (chair, table, sofa and display) using 50 models from each and augmented them 50 times (as per Polygen paper), I noticed that the loss got stuck at 1.17 after 200+ epochs and it would take additional 1-2k epoch to reach 0.7 loss.

But when i upped the codebook 32 768 (x2 increase), it managed to sail though the 1.17 with a breeze.
I then increased the dim_codebook to 384 (x2) and increased the model sizes so the decoder has 48.1M (from 6.8M) and the encoder had 6.1M (from 660k) parameters. 
This made it so it reached 0.7 loss in 68 epochs.

I'm currently testing using  43.9M (decoder) and 8.0M (encoder) with a codebook size of 65 536 using 384 dim_codebook.
I'll let you know what I find, please let me know if you have any other suggestions for how to improve the models the most efficient way rather then just throwing lots of parameters on it 😄

**Comment by MarcusLoppe** [comment]
It seems to save about 700MB using the 6200 face mesh model @ batch size 1, the curve is more linear so it did something :)

But it seems like **"per_sample_entropy = entropy(prob).mean()"** has the most effect on the VRAM, is there any optimization for that?

![bild](https://github.com/lucidrains/meshgpt-pytorch/assets/65302107/7b60918b-1624-42b9-bd90-9cf31c8ac913)

Start of loop = 
`for quantizer_index, layer in enumerate(self.layers):`

# checkpoint_quantize = False #

Start of loop: 3405.0 MB

## Step 1: ##
loop 0  3404.0 MB
`distance = -2 * einsum('... i d, j d -> ... i j', original_input, self.codebook)`
4188.0 MB 
`prob = (-distance * inv_temperature).softmax(dim = -1)`
4588.0 MB    
`per_sample_entropy = entropy(prob).mean()`
5788.0 MB  

loop 1  5788.0 MB
`distance = -2 * einsum('... i d, j d -> ... i j', original_input, self.codebook)`
6192.0 MB  
`prob = (-distance * inv_temperature).softmax(dim = -1)`
6593.0 MB  
`per_sample_entropy = entropy(prob).mean()`
7793.0 MB 

End of loop: 7793.0 MB

## Step 2: ##
1 VRAM Used: 9776.0 MB

loop 0  9776.0 MB
`distance = -2 * einsum('... i d, j d -> ... i j', original_input, self.codebook)`
9776.0 MB  
`prob = (-distance * inv_temperature).softmax(dim = -1)`
9776.0 MB
`per_sample_entropy = entropy(prob).mean()`
9776.0 MB

loop 1  9776.0 MB
`distance = -2 * einsum('... i d, j d -> ... i j', original_input, self.codebook)`
9787.0 MB
prob = (-distance * inv_temperature).softmax(dim = -1)
9787.0 MB
`per_sample_entropy = entropy(prob).mean()`
9787.0 MB 
4 VRAM Used: 9787.0 MB



# checkpoint_quantize = True #

## Step 1: ##

`for quantizer_index, layer in enumerate(self.layers):`
Start of loop: 3387.0 MB 

loop 0  3387.0 MB
`distance = -2 * einsum('... i d, j d -> ... i j', original_input, self.codebook)`
4187.0 MB   
`prob = (-distance * inv_temperature).softmax(dim = -1)`
4587.0 MB 
`per_sample_entropy = entropy(prob).mean()`
5387.0 MB

loop 1  5387.0 MB
`distance = -2 * einsum('... i d, j d -> ... i j', original_input, self.codebook)`
5389.0 MB 
`prob = (-distance * inv_temperature).softmax(dim = -1)`
5399.0 MB  
`per_sample_entropy = entropy(prob).mean()`
5399.0 MB 

End of loop: 5399.0 MB
## Step 2: ##

1 VRAM Used: 5784.0 MB

loop 0  5784.0 MB
`distance = -2 * einsum('... i d, j d -> ... i j', original_input, self.codebook)`
5786.0 MB   
`prob = (-distance * inv_temperature).softmax(dim = -1)`
5786.0 MB  
`per_sample_entropy = entropy(prob).mean()`
6586.0 MB 

Start of loop: 6586.0 MB
`distance = -2 * einsum('... i d, j d -> ... i j', original_input, self.codebook)`
6986.0 MB 
`prob = (-distance * inv_temperature).softmax(dim = -1)`
7396.0 MB  
`per_sample_entropy = entropy(prob).mean()`
8596.0 MB 

End of loop: 8596.0 MB

**Comment by lucidrains** [comment]
@MarcusLoppe thanks for the analysis! could you try reducing [this hyperparameter](https://github.com/lucidrains/meshgpt-pytorch/commit/a9bce242285656c4e20eadfc0ac5ed24abc84058#diff-fc9b595a88c05153593e96003e79fc6f3ac3fa4f3578685b928121a780d7b9f3R398) (to say 0.1) and see if that helps?

**Comment by MarcusLoppe** [comment]
> @MarcusLoppe thanks for the analysis! could you try reducing [this hyperparameter](https://github.com/lucidrains/meshgpt-pytorch/commit/a9bce242285656c4e20eadfc0ac5ed24abc84058#diff-fc9b595a88c05153593e96003e79fc6f3ac3fa4f3578685b928121a780d7b9f3R398) (to say 0.1) and see if that helps?

Ah very nice! It managed to drop down to 3299MB from 6731MB, using 0.5 made it use 5133MB so the relationship is not quite linear. 

I did the same test using fp16 and it went from 4029MB to 2636MB, so training a fp16 model using 6.2k triangles used only 2.6-4GB @ batch size 1.

Other then that test when I've trained the model using fp16 I've noticed a x2 in performance and less memory usage.
The only modification I did was to convert the LFQ codebook and the gaussian_blur_1d function so the distance had the dtype float16.
This might be a downside of fp16 but I got stuck at 0.35 loss, I'm currently checking and using float32 to verify that fp16 was the actual problem or not.

Is it possible to have the LFQ codebook or gaussian_blur_1d using the float32 while the models tensor are in fp16 or is this not possible? I think some of the details might have been lost due to the fp16 type but I don't think it's a overall problem but might just be due to the coodebook and gaussian blur.



# frac_per_sample_entropy = 0.1  #
```
3921.0MB @  Starting loop
4721.0MB @  distance = -2 * einsum(
5121.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
5121.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
5112.0MB @  distance = -2 * einsum(
5074.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
5075.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
5076.0MB @  End of loop
5579.0MB @  Starting loop
5579.0MB @  distance = -2 * einsum(
5979.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
5979.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
6381.0MB @  distance = -2 * einsum(
6781.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
6781.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
6781.0MB @  End of loop
Epoch 1/280:   2%|▏         | 1/50 [00:03<02:41,  3.30s/it, commit_loss=1.04, loss=5.02, recon_loss=4.92]
7210.0MB @  Starting loop
7210.0MB @  distance = -2 * einsum(
7210.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
7210.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
7210.0MB @  distance = -2 * einsum(
7210.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
7210.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
7210.0MB @  End of loop
7220.0MB @  Starting loop
7220.0MB @  distance = -2 * einsum(
7220.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
7220.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
7220.0MB @  distance = -2 * einsum(
7220.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
7220.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
7220.0MB @  End of loop

```


# frac_per_sample_entropy = 0.5 #
```
3901.0MB @  Starting loop
4701.0MB @  distance = -2 * einsum(
5101.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
5501.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
5501.0MB @  distance = -2 * einsum(
5501.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
5485.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
5485.0MB @  End of loop
5785.0MB @  Starting loop
5785.0MB @  distance = -2 * einsum(
6185.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
6985.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
7387.0MB @  distance = -2 * einsum(
7787.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
8587.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
8587.0MB @  End of loop
Epoch 1/280:   2%|▏         | 1/50 [00:03<02:43,  3.34s/it, commit_loss=1.08, loss=5.04, recon_loss=4.93]
9034.0MB @  Starting loop
9034.0MB @  distance = -2 * einsum(
9034.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
9034.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
9034.0MB @  distance = -2 * einsum(
9034.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
9034.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
9034.0MB @  End of loop
9034.0MB @  Starting loop
9034.0MB @  distance = -2 * einsum(
9034.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
9034.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
9034.0MB @  distance = -2 * einsum(
9034.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
9034.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
9034.0MB @  End of loop
```

# frac_per_sample_entropy = 1.0 #
```
3856.0MB @  Starting loop
4656.0MB @  distance = -2 * einsum(
5056.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
5856.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
5856.0MB @  distance = -2 * einsum(
5856.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
5855.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
5829.0MB @  End of loop
6183.0MB @  Starting loop
6183.0MB @  distance = -2 * einsum(
6183.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
7783.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
7785.0MB @  distance = -2 * einsum(
8185.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
9785.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
9785.0MB @  End of loop
Epoch 1/280:   2%|▏         | 1/50 [00:03<02:46,  3.40s/it, commit_loss=1.09, loss=5.13, recon_loss=5.02]
10235.0MB @  Starting loop
10235.0MB @  distance = -2 * einsum(
10235.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
10235.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
10235.0MB @  distance = -2 * einsum(
10235.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
10235.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
10235.0MB @  End of loop
10227.0MB @  Starting loop
10227.0MB @  distance = -2 * einsum(
10227.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
10227.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
10227.0MB @  distance = -2 * einsum(
10227.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
10227.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
10227.0MB @  End of loop
```

# Using fp16 training # 

# frac_per_sample_entropy = 0.1 #
```
3599.0MB @  Starting loop
3999.0MB @  distance = -2 * einsum(
4199.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
4199.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
4199.0MB @  distance = -2 * einsum(
4199.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
4199.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
4190.0MB @  End of loop
5069.0MB @  Starting loop
5451.0MB @  distance = -2 * einsum(
5651.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
5632.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
5828.0MB @  distance = -2 * einsum(
6028.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
6028.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
6028.0MB @  End of loop
Epoch 1/280:   2%|▏         | 1/50 [00:03<02:38,  3.23s/it, commit_loss=1.13, loss=5.1, recon_loss=4.98]
6228.0MB @  Starting loop
6228.0MB @  distance = -2 * einsum(
6228.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
6228.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
6228.0MB @  distance = -2 * einsum(
6228.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
6228.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
6228.0MB @  End of loop
6235.0MB @  Starting loop
6235.0MB @  distance = -2 * einsum(
6235.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
6235.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
6235.0MB @  distance = -2 * einsum(
6235.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
6235.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
6235.0MB @  End of loop
```

# frac_per_sample_entropy = 1.0 #

```
Epoch 1/280:   0%|          | 0/50 [00:00<?, ?it/s]
3756.0MB @  Starting loop
4156.0MB @  distance = -2 * einsum(
4354.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
4748.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
4747.0MB @  distance = -2 * einsum(
4747.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
4747.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
4747.0MB @  End of loop
5193.0MB @  Starting loop
5593.0MB @  distance = -2 * einsum(
5793.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
6592.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
6583.0MB @  distance = -2 * einsum(
6783.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
7583.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
7583.0MB @  End of loop
Epoch 1/280:   2%|▏         | 1/50 [00:03<02:39,  3.26s/it, commit_loss=1.09, loss=5.09, recon_loss=4.98]
7777.0MB @  Starting loop
7777.0MB @  distance = -2 * einsum(
7777.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
7777.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
7777.0MB @  distance = -2 * einsum(
7777.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
7777.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
7777.0MB @  End of loop
7785.0MB @  Starting loop
7785.0MB @  distance = -2 * einsum(
7785.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
7785.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
7785.0MB @  distance = -2 * einsum(
7785.0MB @  prob = (-distance * inv_temperature).softmax(dim = -1
7785.0MB @  per_sample_entropy = entropy(per_sample_probs).mean()
7785.0MB @  End of loop
```

**Comment by lucidrains** [comment]
@MarcusLoppe nice re: memory usage drop! i disabled autocast for LFQ and gaussian blur as well

**Comment by MarcusLoppe** [comment]
> @MarcusLoppe nice re: memory usage drop! i disabled autocast for LFQ and gaussian blur as well

Ah I think i didn't explained it right.
The autocast might have resolved the codebook where I needed to call ".to(dtype=torch.float16)":
`codebook = self.bits_to_codes(bits).to(dtype=torch.float16)`

But the gaussian_blur had the dtype value declared in the arange, since it's explicit declared I'm not sure if the autocast will work(maybe?).
Old:
`distance = torch.arange(-half_width, half_width + 1, dtype = torch.float, device = device)`
My 'fix'
`distance = torch.arange(-half_width, half_width + 1, dtype = torch.float16, device = device)`

**Comment by lucidrains** [comment]
@MarcusLoppe oh got it, reverted the gaussian blur

for quantization, i think it should be kept at f32 to be safe

**Comment by MarcusLoppe** [comment]
> @MarcusLoppe oh got it, reverted the gaussian blur
> 
> for quantization, i think it should be kept at f32 to be safe
>

Probably true, if you smooth the quantized values too much it will be very lossy compression.
It might not be worth it to use fp16 outside of the encoder & decoder, but I'm guessing the data needs to be kept in the same format or else some bad unexpected things might happens. 

However the transformer can probably be trained in fp16 since the reduced probability in the next token doesn't seem to matter went 8/16 bits is used in LLMs.

**Comment by MarcusLoppe** [comment]
@lucidrains  

But this seems like a good solution, I think I'll close the issue since the checkpoint & reducing sample size seems to be working.

However I'm bit unsure about the reducing of the sample size since it just reduces the data it process and not a better way of processing it, but If you think that a smaller sample size if enough to build the codebook I believe you 😄 If not re-open this issue.

**Comment by lucidrains** [comment]
this isn't actually my idea

it is one used all the way back in StyleGAN2

they even have a scheme where for expensive auxiliary losses, they only apply it once every four iterations
