### ISSUE TITLE
transformer.generate()

### ISSUE THREAD

**Issue by gitsawww** [lucidrains/meshgpt-pytorch#41]
Thanks for your grear work!When I run transformer.generate(),it shows as below,how can I solve it?
![image](https://github.com/lucidrains/meshgpt-pytorch/assets/143673887/1e2579ea-1fcb-43eb-b036-c11257b83c33)

**Comment by MarcusLoppe** [comment]
Please provide the whole error message & how you are calling the generate function

**Comment by gitsawww** [comment]
> Please provide the whole error message & how you are calling the generate function
The whole error message is just like this
![image](https://github.com/lucidrains/meshgpt-pytorch/assets/143673887/97f710ff-c301-48bf-a2b6-d71b1ea1f5e6)
and the generate function is below:
![image](https://github.com/lucidrains/meshgpt-pytorch/assets/143673887/6523bc74-fc71-48ba-b742-cfaf9ed76953)

**Comment by MarcusLoppe** [comment]
> > Please provide the whole error message & how you are calling the generate function
> > The whole error message is just like this
> > ![image](https://private-user-images.githubusercontent.com/143673887/293151497-97f710ff-c301-48bf-a2b6-d71b1ea1f5e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NzYwNzgsIm5iZiI6MTcwMzc3NTc3OCwicGF0aCI6Ii8xNDM2NzM4ODcvMjkzMTUxNDk3LTk3ZjcxMGZmLWMzMDEtNDhiZi1hMmI2LWQ3MWIxZWExZjVlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQxNTAyNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDBiMDY3NGQxNzQ2MTFlMWQ0MDJlY2Y3NzJkMjY3YzNmMDk0YThmZmQwMTAwNGUwZDE2MWFmZGRkNGQzZjA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.myhlZm2oBr7-ijdftHXUq1aZBqRYNX0gFWhQwBH4HPQ)



The error message usually have something at the bottom of what actually went wrong. It would be helpful if you paste the entire error message.


> > and the generate function is below:
> > ![image](https://private-user-images.githubusercontent.com/143673887/293152237-6523bc74-fc71-48ba-b742-cfaf9ed76953.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NzYwNzgsIm5iZiI6MTcwMzc3NTc3OCwicGF0aCI6Ii8xNDM2NzM4ODcvMjkzMTUyMjM3LTY1MjNiYzc0LWZjNzEtNDhiYS1iNzQyLWNmYWY5ZWQ3Njk1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQxNTAyNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjM4ZTMwNGE4ODc1YzExZDQ3YmE4NzQ3ODgyOWQ1MTViOTRhMTQyOGQzOTI1YTA4NDA2MmFkNmY0Yzc2M2FhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NaQWyh3LMUG314s-VYjHbPKZJJ-yaP5_zodqvCsLJXM)


Alright, that seems ok since I'm guessing you don't have text enabled.
