### ISSUE TITLE
Training on my own data

### ISSUE THREAD

**Issue by adeerAI** [lucidrains/meshgpt-pytorch#49]
Hi @MarcusLoppe Thanks for your pulled repo, but I was facing a little trouble in the notebook, as I am using Colab instead of Kaggle, could you guide me a little here: tables = load_json("/kaggle/input/shapenet/data.json",2)
Can you also help me that if I have my own data, what should I do then? Much thanks.

**Comment by lucidrains** [comment]
let's move this to discussion or the laion discord
