### ISSUE TITLE
Isn't MeshGPT a VQ-VAE?

### ISSUE THREAD

**Issue by rexxxx1234** [lucidrains/meshgpt-pytorch#53]
Hi guys, thanks for all the work!

I have a conceptual question. Isn't MeshGPT a VQ-VAE? If not, what are the differences? 

Thanks!

**Comment by lucidrains** [comment]
@rexxxx1234 yes you are correct

on a high level, it is DALLE1 applied to mesh generation. but the details matter in this case

**Comment by lucidrains** [comment]
let's move this to discussions
