### ISSUE TITLE
Just to get started

### ISSUE THREAD

**Issue by studiohuahong** [lucidrains/meshgpt-pytorch#60]
Hello there, I'm a designer with basic coding skill but totally unfamilliar with machine learning stuff. Really want to experiment with it. I have install the package and a little confuse about where to start like what data assets should I collect and how to train them. Much appreciate!

**Comment by lucidrains** [comment]
@studiohuahong you should follow the guide that @MarcusLoppe graciously put together https://github.com/lucidrains/meshgpt-pytorch/discussions/51

**Comment by studiohuahong** [comment]
Awesome thank you so much, I'll look into it!
