### ISSUE TITLE
How to view the generated mesh?

### ISSUE THREAD

**Issue by Croolch** [lucidrains/meshgpt-pytorch#7]
Hi, thank you for your code!!
I want to view the mesh and load the faces data into blender. However, the outcome is puzzling. Many faces are overlapping each other.
![image](https://github.com/lucidrains/meshgpt-pytorch/assets/34917945/5b6720b2-14be-46cd-bc78-3ceb2ff84c76)
Is there anything I need to do after I got `faces_coordinates`?

**Comment by Croolch** [comment]
The blender python script is below.

```python
import bpy
import numpy as np

# load faces data
npy_filepath = "faces_coordinates.npy"
faces_coordinates = np.load(npy_filepath)
# shape: (batch, num faces, vertices (3), coordinates (3))

# transform faces_coordinates to blender from_pydata format
# vertices will be a list of coordinates
# faces will be a list of indices of vertices
face_list = faces_coordinates[0]
vertices = []
for face in face_list:
    for vertex in face:
        vertices.append(vertex)

# generate face index
num_faces = len(face_list)
faces = []
for i in range(num_faces):
    face_indices = [3 * i, 3 * i + 1, 3 * i + 2]
    faces.append(face_indices)
print(vertices)

# create mesh
mesh = bpy.data.meshes.new("mesh")
obj = bpy.data.objects.new("mesh", mesh)
bpy.context.scene.collection.objects.link(obj)
mesh.from_pydata(vertices, [], faces)
mesh.update(calc_edges=True)
```
When I give the `faces_coordinates` value as below, there will be a 4 faces mesh.

```python
faces_coordinates = [
    [
        [[0, 0, 0], [1, 0, 0], [0, 1, 0]],
        [[0, 0, 0], [1, 0, 0], [0, 0, 1]],
        [[0, 0, 0], [0, 1, 0], [0, 0, 1]],
        [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
    ]
]
```

![2023-12-12](https://github.com/lucidrains/meshgpt-pytorch/assets/34917945/9f077933-69fb-4f84-a989-3a02fa43e6a1)

Do I have any misunderstanding about the model output?

**Comment by lucidrains** [comment]
you need to train a model on lots of data first

**Comment by Croolch** [comment]
> you need to train a model on lots of data first

oh, it explains a lot. Thank you!
