### ISSUE TITLE
Seeking Collaboration

### ISSUE THREAD

**Issue by xhsyy** [lucidrains/meshgpt-pytorch#81]
Hello, we are a technology company based in China, specialized in CAD, CAE, and other industrial software. Our company plans to integrate AI into our products and business in the future. Recently, we came across your team's implementation of meshgpt on github, and we are very interested. We hope to further discuss or potentially collaborate with you. If you and your team are interested in engaging with us, please reply to this email at pxyang@3vking.com. Thank you very much.

您好，我们是中国的一家科技公司，主做CAD、CAE等工业软件，公司未来想将AI融入到产品和业务中。近日，我们在github上看到了您和团队关于meshgpt的实现，很感兴趣，希望能够进一步交流，或者达成合作。如果您和团队有意与我们接触，烦请回复邮件至邮箱pxyang@3vking.com，非常感谢。

**Comment by lucidrains** [comment]
@xhsyy maybe you can hire @MarcusLoppe , who has done most of the training in this repo

otherwise this is not an official implementation, so you can also try reaching out to the original authors of the paper

**Comment by MarcusLoppe** [comment]
@xhsyy  Hey, I'd be happy to assist. You can reach me logic9950 on discord.
I can share the best practices and tips.

**Comment by xhsyy** [comment]
@MarcusLoppe Hello, I am in China, and my Discord account is always inexplicably banned. Could you please provide an email address so we can communicate through emails?
