### ISSUE TITLE
Area calculation for each triangle is same (with value of 0.5)

### ISSUE THREAD

**Issue by aakash-saboo** [lucidrains/meshgpt-pytorch#83]
Hello! @lucidrains @MarcusLoppe 
I noticed that while calculating the areas of each of the triangle, the cross product is normalized to the value of 1.
In order to get the actual areas, we need to remove the cross product normalization. I have commented the original code line and replaced it with the correct one in the following snippet.

![image](https://github.com/lucidrains/meshgpt-pytorch/assets/39874883/4828b847-5d61-4e1b-90b3-8b4daae62e2d)

**Comment by lucidrains** [comment]
@aakash-saboo oh shoot, thanks for catching this!

are normals unit vectors? i guess it should look something like

```python
cross_product = torch.cross
normals = l2norm(cross_product)
area = cross_product.norm * 0.5
```

**Comment by lucidrains** [comment]
haha, i guess, judging by Marcus' results, the area doesn't matter that much

**Comment by MarcusLoppe** [comment]
> haha, i guess, judging by Marcus' results, the area never mattered that much

Actually area is second most important feature whileI was hyper-tuning the feature dims was the area.
The order of important was; coord, area, norm, angle 
Norm had a small effect and angle had a very little effect.

**Comment by lucidrains** [comment]
@MarcusLoppe yea, but i think it was ablated out because of this error being pointed out

**Comment by lucidrains** [comment]
let me throw in the fix

**Comment by lucidrains** [comment]
if only i knew i would be doing stuff like this today, i would have paid attention in geometry class 😆

**Comment by MarcusLoppe** [comment]
> let me throw in the fix

I retrained my autoencoder with 1 quantizer with this update and the which was kinda of stuck at 0.37 began moving downwards!
Currently it's at 0.35 with 0.04 loss decease per epoch (before it was 0.001).
